### ISSUE TITLE
rendering is taking too much time

### ISSUE THREAD

**Issue by dverma4u** [calvinkei/react-native-mathjax#1]
I am using mathjax with my react-native quiz application. But it is taking too much time in loading the question with all four options and downgrading the performance of application.
I tried putting loader when webview loads but loader stays only untill the webview loads and rending of mathematical questions still takes more time to display.
Any way by which we can reduce the rendering time or put a loader/activity indicator on rending too?

**Comment by calvinkei** [comment]
Hi @dverma4u , I am using this component for the exact same purpose (a multiple choice quiz app with a question and 4 options, and step-by-step solutions, ie 6 mathjax webview to be displayed at the same time) and seems do not have the performance issue you mentioned. It is loaded within 1s like ordinary mathjax in web. Would you mind providing some metrics? Like how long does it take to load and what device are you using?

**Comment by dverma4u** [comment]
It is taking around 5-6 seconds for everything to be loaded. Please help me in reducing this time lag.

**Comment by dverma4u** [comment]
can you please share the quiz app demo? how you are implementing mathJax? Actually I'm only usong the wrapMathkax function from your example app with react-native-webview-autoheight because react-native-autoheight-webview was causing some unresolved error.

**Comment by calvinkei** [comment]
Just fixed some bugs on this module and added demo code on it. it loads almost instantly on my iphone 6 simulator. Please check

**Comment by dverma4u** [comment]
yes, in real device it loads instantly, maybe the issue is with my android emulator.

**Comment by mahesh-vidhate** [comment]
I am facing this same issue on my android device. It is taking 5-6 seconds to load the content. Please help

**Comment by anuragnagarkota** [comment]
I am also facing the same problem.... I guess it is due to the cdn file which is requested every time the webview renders. Is there any way to use the local mathjax lib instead of cdn
