### ISSUE TITLE
Screen keeps updating.

### ISSUE THREAD

**Issue by Pruthvirajcodewave** [calvinkei/react-native-mathjax#10]
Hi i tried using the demo code thats given here. The result is the screen keeps updating itself until only one view is visible. Rest will be moved out of the screen.

The recorded video link is attached here.
[https://drive.google.com/open?id=19TMIZq0X7KAP3ilrMBs-UE7y_nadY5N9](url)

**Comment by calvinkei** [comment]
please update to 2.0.0 to check if the issue persist
