### ISSUE TITLE
Webview "scalesPageToFit={true}" property not work for this library (android)

### ISSUE THREAD

**Issue by ggunti** [calvinkei/react-native-mathjax#18]
I tried to modify the `index.js` file of this library by adding the `scalesPageToFit={true}` property to the WebView like here (I know that `scalesPageToFit` is `true` by default, but it didn't work, so I thought that it may work if I set it manually):
![untitled](https://user-images.githubusercontent.com/26307699/50373232-34524500-05e4-11e9-8451-6c28300a2043.png)

But it didn't work. It still does not scale the webview content:
![bad](https://user-images.githubusercontent.com/26307699/50373261-b5a9d780-05e4-11e9-9d51-3a852c516762.png)

I would like that the loaded page to look like this (without scaling it manually):
![good](https://user-images.githubusercontent.com/26307699/50373268-d114e280-05e4-11e9-94cd-adffaa74b5ed.png)

So my question is: how could be achievied this behaviour?
I also tried to change the default WebView to [react-native-yunpeng-webview](https://github.com/yptech/react-native-yunpeng-webview) WebView, but not worked.

**Comment by ronastlelobo** [comment]
any luck @ggunti ?

**Comment by ggunti** [comment]
unfortunately not, I didn't try to solve it anymore

**Comment by calvinkei** [comment]
Please update to the latest version 2.1.2 and let me know if this issue persist
