### ISSUE TITLE
Broken in Chrome 72

### ISSUE THREAD

**Issue by fredbt** [calvinkei/react-native-mathjax#19]
Hi there,

apparently all webviews that use HTML in the source are broken as of Chrome 72 (see https://github.com/react-native-community/react-native-webview/issues/298).

This also happens with the RN WebView itself (not the new one from RN community). Any ideas of workarounds for this?

**Comment by calvinkei** [comment]
Please update to the latest version 2.1.2 and let me know if this issue persist
