### ISSUE TITLE
The library renders nothing

### ISSUE THREAD

**Issue by saeedtkh** [calvinkei/react-native-mathjax#22]
I have just used the code that you put here as an example and it shows nothing! I checked on both iOS, android, simulators and real devices! Any idea?
My react native version is 57.

**Comment by labinotbjrm** [comment]
Hi @saeedtkh, pres cmd and click MathJax in the code to go inside the MathJax class, then go bottom where WebView component is declared, and change the height of View from this.state.height to 150 (or whatever you want) and run your app.
This worked for me.

**Comment by sadhruva** [comment]
> Hi @saeedtkh, pres cmd (in Windows CTRL) and click MathJax in the code to go inside the MathJax class, then go bottom where WebView component is declared, and change the height of View from this.state.height to 150 (or whatever you want) and run your app.
> This worked for me.

thanks for the answer, but i want dynamic height for dynamic content?

**Comment by calvinkei** [comment]
Please update to the latest version 2.1.2 and let me know if this issue persist
