### ISSUE TITLE
Text is Overflowed instead of showing in next line

### ISSUE THREAD

**Issue by Sahejmaharjan1** [calvinkei/react-native-mathjax#25]

**Comment by calvinkei** [comment]
Please update to the latest version 2.1.2 and let me know if this issue persist

**Comment by amansaxenalapa11** [comment]
long equations horizontal scroll is not working 
i have tried css overflow-x : scroll and overflow-x : auto both.

**Comment by amansaxenalapa11** [comment]
> Please update to the latest version 2.1.2 and let me know if this issue persist

long equations horizontal scroll is not working
i have tried css overflow-x : scroll and overflow-x : auto both.
