### ISSUE TITLE
Showing Mathjax Loading while rendering

### ISSUE THREAD

**Issue by akashjai95** [calvinkei/react-native-mathjax#3]
You can see Mathjax loading screenshot at below link
[https://drive.google.com/file/d/1A3EqrZVlnhkWyOSFGkEtTWjvNrXkHX-k/view?usp=sharing](https://drive.google.com/file/d/1A3EqrZVlnhkWyOSFGkEtTWjvNrXkHX-k/view?usp=sharing)

Is any way to hide??

**Comment by calvinkei** [comment]
I have never experienced this before. What device/simulator are you using?
Also, it might be due to the MathJax configurations which you can change by `mathJaxOptions` props. Try to read through [MathJax documentation](https://docs.mathjax.org/) to see if there's a way to bypass this.

**Comment by calvinkei** [comment]
@akashjai95 refer to this: https://stackoverflow.com/questions/11372615/mathjax-hiding-mathjax-loading-process

i think you can try adding `messageStyle: "none"` to the option

**Comment by akashjai95** [comment]
Thanks now it's working fine.
