### ISSUE TITLE
react-native link react-native-mathjax not working for android

### ISSUE THREAD

**Issue by Pruthvirajcodewave** [calvinkei/react-native-mathjax#9]
When i try react-native link react-native-mathjax i am getting the fallowing response in command line.

"rnpm-install info Platform 'ios' module react-native-mathjax is already linked "

Tried "react-native link react-native-mathjax android" this command also but getting the same response. 

Fallowing are the verions used.
react-native-cli: 2.0.1
react-native: 0.56.0

**Comment by calvinkei** [comment]
if you have already linked it then it's fine, just ignore the message.
the problem is does it work after linking the module? if not what's the error?

**Comment by Pruthvirajcodewave** [comment]
Hi calvinkei,
The question was i am not able to link to android. Even when i try to link to android also with fallowing syntax `react-native link react-native-mathjax android` its giving me same error. 
Please clarify.

**Comment by cuihs** [comment]
I have the same problem. react-native-mathjax is not work for me.

**Comment by calvinkei** [comment]
please update to 2.0.0 (`react-native link` not required!)
